name: Apply terraform plan

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform plan
    init:
      uses: WhiteTomX/microsoft-teams-apps-icebreaker/.github/workflows/init.yaml@ca0892ddb184f2bdb84caf6c699927e5ab1cf60d
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: my-terraform-config