name: Apply terraform plan

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform plan
    environment: zgm-int
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: init
      uses: ./.github/actions/init
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
        arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
        arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
    - name: terraform-apply
      uses: dflook/terraform-apply@v1
      with:
        path: ${{ env.TF_DIR }}
    - name: Get outputs
      uses: dflook/terraform-output@v1
      id: tf-outputs
      with:
        path: ${{ env.TF_DIR }}
    - name: Upload App Package
      uses: actions/upload-artifact@v2
      with:
        name: App-Package
        path: ${{ steps.tf-outputs.outputs.manifest_path }}
        if-no-files-found: error