name: Apply terraform plan

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform plan
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: init
      uses: ./.github/actions/init

    - name: terraform apply
      uses: dflook/terraform-apply@v1
      with:
        path: ${{ env.TF_DIR }}