name: Create terraform plan

on: [pull_request]

jobs:
  plan:
    name: Plan
    runs-on: Ubuntu-latest
    steps:
      - name: init
        uses: ./.github/actions/init.yaml
      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: ${{ env.TF_DIR }}