name: Create terraform plan

on: [pull_request]

jobs:
  plan:
    name: Plan
    runs-on: Ubuntu-latest
    environment: zgm-int
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: init
      uses: ./.github/actions/init
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
        arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
        arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
    - name: terraform plan
      uses: dflook/terraform-plan@v1
      with:
        path: ${{ env.TF_DIR }}
  build:
    name: Build
    runs-on: Windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: build
      uses: ./.github/actions/build
      with:
        source_path: Source