name: Test

on: [push]

jobs:
  test:
    runs-on: windows-latest
    name: Test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: build
      uses: ./.github/actions/build
      with:
        source_path: Source
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
    - name: Run Tests
      run: vstest.console.exe ${{ github.workspace }}/out/Icebreaker.Tests.dll