name: Test

on: [push]

jobs:
  test:
    runs-on: windows-latest
    name: Test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: build
      uses: ./.github/actions/build
      with:
        source_path: Source
    - name: Run Tests
      uses: microsoft/vstest-action@v1.0.0
      with:
        testAssembly: Icebreaker.Tests.dll
        searchFolder: "${{ github.workspace }}/out"
        runInParallel: true