name: Test

on: [push]

jobs:
  test:
    runs-on: windows-latest
    name: Test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: build
      uses: ./.github/actions/build
      with:
        source_path: Source
    - name: find
      run: Get-ChildItem -Recurse -Path "${{ env.GITHUB_WORKSPACE }}/out" | select -ExpandProperty FullName
    - name: Run Tests
      uses: microsoft/vstest-action@v1.0.0
      with:
        testAssembly: Icebreaker.Tests*.dll
        searchFolder: "${{ env.GITHUB_WORKSPACE }}/out/_PublishedWebsites/Icebreaker.Tests"
        runInParallel: true